### PR TITLE
Add Mistral Instruct - Requesting Review

### PR DESCRIPTION
**Pull request by LumiWasTaken**
Heya, 

i've laid out the Basics for the Mistral Instruct to be added. 

I was going by this Documentation:
https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1

Which in the bottom has:
[INST] Instruction [/INST] Model answer [INST] Follow-up instruction [/INST]

(<s> and </s> excluded)

Though I've struggled with the Construct surrounding how the messages / Prompt is put together.

In it's current state this pull request seems to have flaws.

### CODE REVIEW

**Comment by alicat22** [comment]
I'm not aware of `System:` or `User:` or `Assistant:` being included in the original Mistral instruct template. As a result, I would highly suggest leaving it up to the individual and not forcing it as that can not only be detrimental to quality but flexibility and usability, as well.

The correct tokens are `[INST] ` and ` [/INST]`, so if the code does that, then perfect!

**Comment by LumiWasTaken** [comment]
@alicat22 @thesentinel2615 

Heya, requesting a review.

I have done the following:

Because the Initial "header" of the Construct is already pre-defined before the check if mixstral vicuna etc. comes i had to do a little trickery. It's horrible and kind of ugly having the check there and kind of reaching deep into the start of the function (formatCompletionRequest) but it does the job.

In my testing this makes many Models that rely on the [INST] [/INST] format very useable and quite enjoyable.

I'd highly suggest for an alternative system to be implemented e.g. handlebars.


Right now the Code produces a format which looks like this:

`[INST] Write Audrey's next reply in this fictional roleplay with lumifumi.

Audrey Description

Audrey Personality

Audrey Scenario

Message Examples

[INST] lumifumi: Heya, who are you wtf? [/INST]
Audrey: *rolling her eyes* I'm Audrey, and I don't have time for your bullshit. What do you want?
[INST] lumifumi: So what do you usually do? [/INST]
Audrey:`

It's been a painful time to understand this.

**Comment by alicat22** [comment]
I'd personally suggest:
```
Write Audrey's next reply in this fictional roleplay with lumifumi.
Audrey Description
Audrey Personality
Audrey Scenario
Message Examples
[INST] lumifumi: Heya, who are you wtf? [/INST]
Audrey: *rolling her eyes* I'm Audrey, and I don't have time for your bullshit. What do you want?
[INST] lumifumi: So what do you usually do? [/INST]
Audrey:
```
or the following, which would be even more accurate:
```
Write Audrey's next reply in this fictional roleplay with lumifumi.
Audrey Description
Audrey Personality
Audrey Scenario
Message Examples
[INST] lumifumi: Heya, who are you wtf? [/INST] Audrey: *rolling her eyes* I'm Audrey, and I don't have time for your bullshit. What do you want? [INST] lumifumi: So what do you usually do? [/INST] Audrey:
```
Mistral doesn't have a system prefix. Forcing empty newlines is also ill-advised. If someone wants to add in their own empty newlines, they're still able to do so since those aren't trimmed. If someone wants to manually add `[INST]` `[/INST]` to the system prompt they're still able to do so, I don't think forcing it is ever a good idea, especially since it's not even used in the official template.

**Comment by LumiWasTaken** [comment]
Interesting, i have been copying what silly tavern did so i'm surprised.

If thats the case i could've saved myself a lot of headache for the bottom one instead of basically taking apart the entire processing to get to the system prompt x.x"

**Pull request merged**
